language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then cd aliyun-python-sdk-core; else cd aliyun-python-sdk-core-v3; fi
  - python setup.py install
  - pytest -s integration/
